# Generated by Django 4.0 on 2021-12-26 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.destination')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='order.order')),
            ],
        ),
    ]
